name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>Great to see you here!</h1> <br><br> Welcome to the community :tada: <br> Thank you for your valuable contributions! 🚀 We appreciate every and single contribution! 😄 <br><br> <h2>Join our amazing community 📢</h2> <br><br> Join our community to learn more about Blockchain, Web3, Dapps, and so much more 💻 <br><br> Here you can find all of our socials! 🐦 Share them with your friends and everyone you know. <br><br> - [Discord server](https://discord.gg/VwJp4KM) <br> - [Twitter](http://twitter.com/devprtcl) <br> - [LinkedIn](https://www.linkedin.com/company/dev-protocol) <br> - [Telegram](https://t.me/devprotocol) <br> - [YouTube](https://www.youtube.com/channel/UCN7m74tFgJJnoGL4zk6aJ6g) <br> - [Facebook](https://www.facebook.com/DevProtocol.xyz/) <br><br> We hope to see you there! 😁'
          pr-message: '<h1>Great to see you here!</h1> <br><br> Welcome to the community :tada: <br> Thank you for your valuable contributions! 🚀 We appreciate every and single contribution! 😄 <br><br> <h2>Join our amazing community 📢</h2> <br><br> Join our community to learn more about Blockchain, Web3, Dapps, and so much more 💻 <br><br> Here you can find all of our socials! 🐦 Share them with your friends and everyone you know. <br><br> - [Discord server](https://discord.gg/VwJp4KM) <br> - [Twitter](http://twitter.com/devprtcl) <br> - [LinkedIn](https://www.linkedin.com/company/dev-protocol) <br> - [Telegram](https://t.me/devprotocol) <br> - [YouTube](https://www.youtube.com/channel/UCN7m74tFgJJnoGL4zk6aJ6g) <br> - [Facebook](https://www.facebook.com/DevProtocol.xyz/) <br><br> We hope to see you there! 😁'
